"""
Data lineage models based on W3C PROV Data Model.

Provides Pydantic models for tracking data provenance:
- Entity: Data artefacts (input files, generated personas, etc.)
- Activity: Transformations that use and generate entities
- Agent: Tools, models, or users that perform activities

Reference: https://www.w3.org/TR/prov-dm/
"""

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class EntityType(str, Enum):
    """Types of entities in the lineage graph."""

    INPUT_FILE = "input_file"
    INPUT_DATA = "input_data"
    PROMPT = "prompt"
    LLM_RESPONSE = "llm_response"
    PERSONA = "persona"
    PERSONA_SET = "persona_set"
    EXPORT = "export"
    CONFIG = "config"
    TEMPLATE = "template"


class ActivityType(str, Enum):
    """Types of activities in the lineage graph."""

    DATA_LOAD = "data_load"
    DATA_TRANSFORM = "data_transform"
    PROMPT_RENDER = "prompt_render"
    LLM_GENERATION = "llm_generation"
    PERSONA_PARSE = "persona_parse"
    PERSONA_VALIDATE = "persona_validate"
    PERSONA_REFINE = "persona_refine"
    PERSONA_EXPORT = "persona_export"
    QUALITY_CHECK = "quality_check"


class AgentType(str, Enum):
    """Types of agents in the lineage graph."""

    USER = "user"
    CLI_TOOL = "cli_tool"
    LLM_MODEL = "llm_model"
    VALIDATOR = "validator"
    EXPORTER = "exporter"


class LineageEntity(BaseModel):
    """
    An entity in the data lineage graph.

    Entities are data artefacts that can be used or generated by activities.
    Each entity has a content hash for integrity verification.

    Example:
        ```python
        entity = LineageEntity(
            entity_id="e-123",
            entity_type=EntityType.INPUT_FILE,
            name="interviews.csv",
            hash="sha256:abc123...",
            path="/data/interviews.csv"
        )
        ```

    Attributes:
        entity_id: Unique identifier for this entity.
        entity_type: Type of entity (input, persona, etc.).
        name: Human-readable name.
        hash: Content hash (sha256:...) for verification.
        path: File path if applicable.
        metadata: Additional metadata about the entity.
        generated_by: Activity ID that generated this entity.
        generated_at: When the entity was created.
    """

    entity_id: str = Field(..., description="Unique entity identifier")
    entity_type: EntityType = Field(..., description="Type of entity")
    name: str = Field(..., description="Human-readable name")
    hash: str = Field(..., description="Content hash (sha256:...)")
    path: str | None = Field(default=None, description="File path if applicable")
    size_bytes: int | None = Field(default=None, description="Size in bytes")
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional metadata",
    )
    generated_by: str | None = Field(
        default=None,
        description="Activity ID that generated this entity",
    )
    generated_at: datetime = Field(
        default_factory=datetime.now,
        description="When the entity was created",
    )

    model_config = ConfigDict(use_enum_values=True)


class LineageActivity(BaseModel):
    """
    An activity in the data lineage graph.

    Activities are transformations that use entities as inputs and
    generate new entities as outputs.

    Example:
        ```python
        activity = LineageActivity(
            activity_id="a-456",
            activity_type=ActivityType.LLM_GENERATION,
            name="Generate personas",
            agent_id="agent-789",
            used_entities=["e-input"],
            generated_entities=["e-output-1", "e-output-2"]
        )
        ```

    Attributes:
        activity_id: Unique identifier for this activity.
        activity_type: Type of activity.
        name: Human-readable name.
        agent_id: Agent that performed this activity.
        run_id: Optional link to experiment run.
        used_entities: Entity IDs that were inputs.
        generated_entities: Entity IDs that were outputs.
        parameters: Parameters used for this activity.
        started_at: When the activity started.
        ended_at: When the activity ended.
        status: Activity status (running, completed, failed).
    """

    activity_id: str = Field(..., description="Unique activity identifier")
    activity_type: ActivityType = Field(..., description="Type of activity")
    name: str = Field(..., description="Human-readable name")
    agent_id: str = Field(..., description="Agent that performed this activity")
    run_id: str | None = Field(
        default=None,
        description="Link to experiment run (F-124)",
    )
    used_entities: list[str] = Field(
        default_factory=list,
        description="Entity IDs used as inputs",
    )
    generated_entities: list[str] = Field(
        default_factory=list,
        description="Entity IDs generated as outputs",
    )
    parameters: dict[str, Any] = Field(
        default_factory=dict,
        description="Parameters used for this activity",
    )
    started_at: datetime = Field(
        default_factory=datetime.now,
        description="When the activity started",
    )
    ended_at: datetime | None = Field(
        default=None,
        description="When the activity ended",
    )
    status: str = Field(default="running", description="Activity status")

    model_config = ConfigDict(use_enum_values=True)


class LineageAgent(BaseModel):
    """
    An agent in the data lineage graph.

    Agents are tools, models, or users that perform activities.

    Example:
        ```python
        agent = LineageAgent(
            agent_id="agent-789",
            agent_type=AgentType.LLM_MODEL,
            name="claude-sonnet-4-20250514",
            version="2025-05-14",
            provider="anthropic"
        )
        ```

    Attributes:
        agent_id: Unique identifier for this agent.
        agent_type: Type of agent.
        name: Agent name (model ID, tool name, etc.).
        version: Version string.
        provider: Provider or vendor name.
        metadata: Additional metadata about the agent.
    """

    agent_id: str = Field(..., description="Unique agent identifier")
    agent_type: AgentType = Field(..., description="Type of agent")
    name: str = Field(..., description="Agent name")
    version: str | None = Field(default=None, description="Version string")
    provider: str | None = Field(default=None, description="Provider or vendor")
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional metadata",
    )

    model_config = ConfigDict(use_enum_values=True)


class LineageRelation(BaseModel):
    """
    A relationship in the lineage graph.

    Represents PROV relationships:
    - wasGeneratedBy: Entity was generated by Activity
    - used: Activity used Entity
    - wasAttributedTo: Entity was attributed to Agent
    - wasAssociatedWith: Activity was associated with Agent
    - wasDerivedFrom: Entity was derived from another Entity
    """

    relation_type: str = Field(..., description="Type of relation")
    source_id: str = Field(..., description="Source node ID")
    target_id: str = Field(..., description="Target node ID")
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Relation metadata",
    )


class LineageGraph(BaseModel):
    """
    Complete lineage graph containing all nodes and relationships.

    Used for serialisation and PROV-JSON export.
    """

    entities: list[LineageEntity] = Field(default_factory=list)
    activities: list[LineageActivity] = Field(default_factory=list)
    agents: list[LineageAgent] = Field(default_factory=list)
    relations: list[LineageRelation] = Field(default_factory=list)

    def to_prov_dict(self) -> dict[str, Any]:
        """
        Convert to PROV-JSON format.

        Returns:
            Dictionary conforming to PROV-JSON schema.
        """
        prov: dict[str, Any] = {
            "prefix": {
                "persona": "https://github.com/REPPL/Persona/ns#",
                "prov": "http://www.w3.org/ns/prov#",
            },
            "entity": {},
            "activity": {},
            "agent": {},
        }

        # Add entities
        for entity in self.entities:
            prov["entity"][f"persona:{entity.entity_id}"] = {
                "prov:type": entity.entity_type,
                "persona:name": entity.name,
                "persona:hash": entity.hash,
            }
            if entity.path:
                prov["entity"][f"persona:{entity.entity_id}"]["persona:path"] = (
                    entity.path
                )

        # Add activities
        for activity in self.activities:
            prov["activity"][f"persona:{activity.activity_id}"] = {
                "prov:type": activity.activity_type,
                "persona:name": activity.name,
                "prov:startTime": activity.started_at.isoformat(),
            }
            if activity.ended_at:
                prov["activity"][f"persona:{activity.activity_id}"]["prov:endTime"] = (
                    activity.ended_at.isoformat()
                )

        # Add agents
        for agent in self.agents:
            prov["agent"][f"persona:{agent.agent_id}"] = {
                "prov:type": agent.agent_type,
                "persona:name": agent.name,
            }
            if agent.version:
                prov["agent"][f"persona:{agent.agent_id}"]["persona:version"] = (
                    agent.version
                )
            if agent.provider:
                prov["agent"][f"persona:{agent.agent_id}"]["persona:provider"] = (
                    agent.provider
                )

        # Add relationships
        relations_by_type: dict[str, list[dict]] = {}
        for relation in self.relations:
            if relation.relation_type not in relations_by_type:
                relations_by_type[relation.relation_type] = []
            relations_by_type[relation.relation_type].append(
                {
                    "prov:entity": f"persona:{relation.source_id}",
                    "prov:activity": f"persona:{relation.target_id}",
                }
            )

        for rel_type, rels in relations_by_type.items():
            prov[rel_type] = {f"_:{i}": rel for i, rel in enumerate(rels)}

        return prov
